kind = "web"
previewPath = "/"
title = "Minecraft Website"
version = "1.0.0"
id = "artifacts/minecraft-site"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23944

[services.development]
run = "pnpm --filter @workspace/minecraft-site run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/minecraft-site", "run", "build" ]
publicDir = "artifacts/minecraft-site/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23944"
BASE_PATH = "/"
